name: Test
on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
        - uses: actions/setup-go@v4
          with:
              go-version: 1.19
        - uses: actions/checkout@v4
        - name: golangci-lint
          uses: golangci/golangci-lint-action@v3

  unit:
    name: Unit
    runs-on: ubuntu-latest
    steps:
        - uses: actions/setup-go@v4
          with:
              go-version: 1.19
        - uses: actions/checkout@v4
        - name: Vendors
          run: make vendors
        - name: Unit test
          run: make test
